import { jsPDF } from 'jspdf';

export const generatePDF = (formData, topics) => {
    console.log(`[PDF Gen] Creating PDF for: ${formData.companyName} (${formData.trade})`);

    const doc = new jsPDF()

    // 1. COVER PAGE
    doc.setFillColor(17, 24, 39) // Brand Black
    doc.rect(0, 0, 210, 297, "F")

    doc.setTextColor(251, 191, 36) // Brand Yellow
    doc.setFontSize(40)
    doc.setFont(undefined, 'bold')
    doc.text("2025 SAFETY", 105, 100, null, null, "center")
    doc.text("SCHEDULE", 105, 115, null, null, "center")

    doc.setTextColor(255, 255, 255)
    doc.setFontSize(16)
    doc.setFont(undefined, 'normal')
    doc.text(`Prepared for: ${formData.companyName}`, 105, 140, null, null, "center")
    if (formData.safetyOfficer) {
        doc.text(`Safety Officer: ${formData.safetyOfficer}`, 105, 150, null, null, "center")
    }
    doc.text(`Trade Focus: ${formData.trade}`, 105, 160, null, null, "center")
    doc.text("Generated by TurboToolbox.com", 105, 270, null, null, "center")

    // 2. SCHEDULE PAGES
    doc.addPage()
    doc.setTextColor(0, 0, 0)

    let y = 20
    doc.setFontSize(18)
    doc.setFont(undefined, 'bold')
    doc.text(`Weekly Safety Topics - ${formData.companyName}`, 20, y)

    y += 15

    // Table Header
    doc.setFillColor(240, 240, 240)
    doc.rect(15, y - 8, 180, 10, "F")
    doc.setFontSize(10)
    doc.text("DATE", 20, y)
    doc.text("TOPIC & DESCRIPTION", 50, y)
    doc.text("SIGNATURE", 160, y)
    y += 10

    doc.setFont(undefined, 'normal')
    doc.setFontSize(9)

    const getWeekDate = (startStr, weekIndex) => {
        const date = new Date(startStr);
        date.setDate(date.getDate() + (weekIndex * 7));
        return date.toLocaleDateString('en-US', { month: 'short', day: 'numeric' });
    }

    topics.forEach((topic, index) => {
        if (y > 270) {
            doc.addPage()
            y = 20
            doc.setFont(undefined, 'bold')
            doc.setFontSize(18)
            doc.text(`Weekly Safety Topics (Cont.)`, 20, y)
            y += 15
            doc.setFillColor(240, 240, 240)
            doc.rect(15, y - 8, 180, 10, "F")
            doc.setFontSize(10)
            doc.text("DATE", 20, y)
            doc.text("TOPIC & DESCRIPTION", 50, y)
            doc.text("SIGNATURE", 160, y)
            y += 10
            doc.setFont(undefined, 'normal')
            doc.setFontSize(9)
        }

        const weekDate = getWeekDate(formData.startDate, index);

        doc.setFont(undefined, 'bold')
        doc.text(weekDate, 20, y)
        doc.text(topic.title, 50, y)
        doc.text("_______________________", 160, y)

        let description = topic.desc;
        doc.setFont(undefined, 'normal')
        doc.setTextColor(100, 100, 100)
        doc.text(description, 50, y + 4)
        doc.setTextColor(0, 0, 0)

        y += 12
    })

    // 3. FULL MODULES
    topics.forEach((topic, index) => {
        doc.addPage();

        // Header
        doc.setFillColor(17, 24, 39);
        doc.rect(0, 0, 210, 30, "F");

        doc.setTextColor(251, 191, 36);
        doc.setFontSize(22);
        doc.setFont(undefined, 'bold');
        doc.text(`WEEK ${index + 1}: TRAINING MODULE`, 105, 15, null, null, "center");

        // OSHA Ref Badge
        if (topic.oshaRef) {
            doc.setFillColor(220, 38, 38); // Red
            doc.rect(140, 40, 50, 8, "F");
            doc.setTextColor(255, 255, 255);
            doc.setFontSize(10);
            doc.text(`OSHA: ${topic.oshaRef}`, 165, 45, null, null, "center");
        }

        doc.setTextColor(0, 0, 0);
        doc.setFontSize(24);
        doc.text(doc.splitTextToSize(topic.title, 130), 20, 50);

        doc.setFontSize(12);
        doc.setFont(undefined, 'normal');
        doc.setTextColor(80, 80, 80);
        doc.text(doc.splitTextToSize(topic.desc, 170), 20, 65);

        let cursorY = 85;

        // "Real World" Story Box
        if (topic.story) {
            doc.setFillColor(243, 244, 246); // Gray
            doc.setDrawColor(209, 213, 219);
            doc.rect(20, cursorY, 170, 20, "FD");

            doc.setFont(undefined, 'bold');
            doc.setTextColor(17, 24, 39);
            doc.text("⚠️ REAL WORLD INCIDENT:", 25, cursorY + 6);

            doc.setFont(undefined, 'italic');
            doc.setFontSize(10);
            doc.setTextColor(55, 65, 81);
            doc.text(doc.splitTextToSize(topic.story, 160), 25, cursorY + 12);

            cursorY += 28;
        }

        // Trainer Notes
        if (topic.trainerNotes) {
            doc.setFillColor(255, 251, 235);
            doc.setDrawColor(251, 191, 36);
            doc.rect(20, cursorY, 170, 25, "FD");

            doc.setFont(undefined, 'bold');
            doc.setFontSize(12);
            doc.setTextColor(180, 83, 9);
            doc.text("FOREMAN NOTES:", 25, cursorY + 7);

            doc.setFont(undefined, 'normal');
            doc.setTextColor(0, 0, 0);
            doc.text(doc.splitTextToSize(topic.trainerNotes, 160), 25, cursorY + 15);

            cursorY += 35;
        }

        // Talking Points
        doc.setFontSize(16);
        doc.setFont(undefined, 'bold');
        doc.setTextColor(0, 0, 0);
        doc.text("Key Discussion Points", 20, cursorY);
        cursorY += 10;

        doc.setFontSize(12);
        doc.setFont(undefined, 'normal');

        const points = topic.talkingPoints || ["Review hazards."];
        points.forEach(point => {
            doc.text(`• ${point}`, 25, cursorY);
            cursorY += 10;
        });

        cursorY += 10;

        // Checklist (New)
        if (topic.checklist) {
            doc.setFontSize(16);
            doc.setFont(undefined, 'bold');
            doc.text("Inspection Checklist", 20, cursorY);
            cursorY += 10;

            doc.setFontSize(12);
            doc.setFont(undefined, 'normal');
            topic.checklist.forEach(item => {
                doc.rect(25, cursorY - 4, 4, 4); // Box
                doc.text(item, 35, cursorY);
                cursorY += 10;
            });
            cursorY += 5;
        }

        // Quiz
        if (topic.quiz) {
            doc.setDrawColor(200, 200, 200);
            doc.line(20, cursorY, 190, cursorY);
            cursorY += 10;

            doc.setFont(undefined, 'bold');
            doc.text("Quick Quiz:", 20, cursorY);
            doc.setFont(undefined, 'normal');
            doc.text(`Q: ${topic.quiz.question}`, 50, cursorY);
            cursorY += 8;
            doc.setFont(undefined, 'italic');
            doc.setTextColor(100, 100, 100);
            doc.text(`A: ${topic.quiz.answer}`, 50, cursorY);
            doc.setTextColor(0, 0, 0);
            doc.setFont(undefined, 'normal');
        }

        // Signatures
        const bottomY = 250;
        doc.setFontSize(14);
        doc.setFont(undefined, 'bold');
        doc.text("Crew Sign-in", 20, bottomY);
        doc.setFontSize(10);
        doc.setFont(undefined, 'normal');
        doc.text("By signing below, I acknowledge hazards discussed.", 20, bottomY + 6);

        let sigY = bottomY + 15;
        doc.line(20, sigY, 190, sigY);
        doc.text("Name", 25, sigY + 5);
        doc.text("Signature", 110, sigY + 5);

        for (let i = 0; i < 3; i++) {
            sigY += 10;
            doc.line(20, sigY, 190, sigY);
        }
    });

    doc.save(`${formData.companyName.replace(/\s+/g, '_')}_Safety_Schedule.pdf`)
}
